
chezmoi add ~/.config/btop
chezmoi add ~/.config/cava
chezmoi add ~/.config/corectrl
chezmoi add ~/.config/dunst
chezmoi add ~/.config/fastfetch
chezmoi add ~/.config/fish
chezmoi add ~/.config/foot
chezmoi add ~/.config/goverlay
chezmoi add ~/.config/htop
chezmoi add ~/.config/hypr
chezmoi add ~/.config/hyprland-autoname-workspaces
chezmoi add ~/.config/input-remapper-2
chezmoi add ~/.config/kitty
chezmoi add ~/.config/Kvantum
chezmoi add ~/.config/lazygit
chezmoi add ~/.config/mako
chezmoi add ~/.config/MangoHud
chezmoi add ~/.config/micro
chezmoi add ~/.config/mpv
chezmoi add ~/.config/neofetch
chezmoi add ~/.config/nvim
chezmoi add ~/.config/OpenRGB
chezmoi add ~/.config/rofi
chezmoi add ~/.config/swappy
chezmoi add ~/.config/swaylock
chezmoi add ~/.config/swaync
chezmoi add ~/.config/tabliss
chezmoi add ~/.config/Thunar
chezmoi add ~/.config/wal
chezmoi add ~/.config/waybar
chezmoi add ~/.config/wofi
chezmoi add ~/.config/kdeglobals
chezmoi add ~/.config/starship.toml
chezmoi add ~/Pictures/wallpapers
chezmoi add ~/.config/scripts
chezmoi add ~/.config/matugen
chezmoi add ~/.config/qt5ct
chezmoi add ~/.config/qt6ct
chezmoi add ~/.config/ags
chezmoi add ~/.config/gtk-2.0
chezmoi add ~/.config/gtk-3.0
chezmoi add ~/.config/gtk-4.0
chezmoi add ~/.config/zathura
chezmoi add ~/.config/menus
chezmoi add ~/.config/wallust