
cp -r ~/.config/btop ./dot_config/btop
cp -r ~/.config/cava ./dot_config/cava
cp -r ~/.config/corectrl ./dot_config/corectrl
cp -r ~/.config/dunst ./dot_config/dunst
cp -r ~/.config/fastfetch ./dot_config/fastfetch
cp -r ~/.config/fish ./dot_config/fish
cp -r ~/.config/foot ./dot_config/foot
cp -r ~/.config/goverlay ./dot_config/goverlay
cp -r ~/.config/htop ./dot_config/htop
cp -r ~/.config/hypr ./dot_config/hypr
cp -r ~/.config/hyprland-autoname-workspaces ./dot_config/hyprland-autoname-workspaces
cp -r ~/.config/input-remapper-2 ./dot_config/input-remapper-2
cp -r ~/.config/kitty ./dot_config/kitty
cp -r ~/.config/Kvantum ./dot_config/Kvantum
cp -r ~/.config/lazygit ./dot_config/lazygit
cp -r ~/.config/MangoHud ./dot_config/MangoHud
cp -r ~/.config/micro ./dot_config/micro
cp -r ~/.config/mpv ./dot_config/mpv
cp -r ~/.config/nvim ./dot_config/nvim
cp -r ~/.config/OpenRGB ./dot_config/OpenRGB
cp -r ~/.config/rofi ./dot_config/rofi
cp -r ~/.config/swappy ./dot_config/swappy
cp -r ~/.config/swaylock ./dot_config/swaylock
cp -r ~/.config/swaync ./dot_config/swaync
cp -r ~/.config/tabliss ./dot_config/tabliss
cp -r ~/.config/Thunar ./dot_config/Thunar
cp -r ~/.config/wal ./dot_config/wal
cp -r ~/.config/waybar ./dot_config/waybar
cp -r ~/.config/kdeglobals ./dot_config/kdeglobals
cp -r ~/.config/starship.toml ./dot_config/starship.toml
cp -r ~/Pictures/wallpapers ./dot_config/wallpapers
cp -r ~/.config/scripts ./dot_config/scripts
cp -r ~/.config/matugen ./dot_config/matugen
cp -r ~/.config/qt5ct ./dot_config/qt5ct
cp -r ~/.config/qt6ct ./dot_config/qt6ct
cp -r ~/.config/ags ./dot_config/ags
cp -r ~/.config/gtk-2.0 ./dot_config/gtk-2.0
cp -r ~/.config/gtk-3.0 ./dot_config/gtk-3.0
cp -r ~/.config/gtk-4.0 ./dot_config/gtk-4.0
cp -r ~/.config/zathura ./dot_config/zathura
cp -r ~/.config/menus ./dot_config/menus
cp -r ~/.config/wallust ./dot_config/wallust
cp -r ~/.config/waypaper ./dot_config/waypaper